
package intrashipservice.ws.de.isservice_1_0_de;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ISService_1_0_de", targetNamespace = "http://de.ws.intrashipservice", wsdlLocation = "ISService_1_0_de.wsdl")
public class ISService10DeClient
    extends Service
{

    private final static URL ISSERVICE10DE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(intrashipservice.ws.de.isservice_1_0_de.ISService10DeClient.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = intrashipservice.ws.de.isservice_1_0_de.ISService10DeClient.class.getResource(".");
            url = new URL(baseUrl, "ISService_1_0_de.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'ISService_1_0_de.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ISSERVICE10DE_WSDL_LOCATION = url;
    }

    public ISService10DeClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ISService10DeClient() {
        super(ISSERVICE10DE_WSDL_LOCATION, new QName("http://de.ws.intrashipservice", "ISService_1_0_de"));
    }

    /**
     * 
     * @return
     *     returns ISWSServicePortType
     */
    @WebEndpoint(name = "ShipmentServiceSOAP11port0")
    public ISWSServicePortType getShipmentServiceSOAP11Port0() {
        return super.getPort(new QName("http://de.ws.intrashipservice", "ShipmentServiceSOAP11port0"), ISWSServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ISWSServicePortType
     */
    @WebEndpoint(name = "ShipmentServiceSOAP11port0")
    public ISWSServicePortType getShipmentServiceSOAP11Port0(WebServiceFeature... features) {
        return super.getPort(new QName("http://de.ws.intrashipservice", "ShipmentServiceSOAP11port0"), ISWSServicePortType.class, features);
    }

}
