
package intrashipservice.ws.de.isservice_1_0_de;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import intraship.ws.de.BookPickupRequest;
import intraship.ws.de.BookPickupResponse;
import intraship.ws.de.CancelPickupRequest;
import intraship.ws.de.CancelPickupResponse;
import intraship.ws.de.CreateShipmentDDRequest;
import intraship.ws.de.CreateShipmentResponse;
import intraship.ws.de.CreateShipmentTDRequest;
import intraship.ws.de.DeleteShipmentDDRequest;
import intraship.ws.de.DeleteShipmentResponse;
import intraship.ws.de.DeleteShipmentTDRequest;
import intraship.ws.de.DoManifestDDRequest;
import intraship.ws.de.DoManifestResponse;
import intraship.ws.de.DoManifestTDRequest;
import intraship.ws.de.GetExportDocDDRequest;
import intraship.ws.de.GetExportDocResponse;
import intraship.ws.de.GetExportDocTDRequest;
import intraship.ws.de.GetLabelDDRequest;
import intraship.ws.de.GetLabelResponse;
import intraship.ws.de.GetLabelTDRequest;
import intraship.ws.de.GetManifestDDRequest;
import intraship.ws.de.GetManifestDDResponse;
import intraship.ws.de.GetVersionResponse;
import intraship.ws.de.UpdateShipmentDDRequest;
import intraship.ws.de.UpdateShipmentResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ISWSServicePortType", targetNamespace = "http://de.ws.intrashipservice")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    intraship.ws.de.ObjectFactory.class,
    intrashipservice.ws.de.isservice_1_0_de.ObjectFactory.class
})
public interface ISWSServicePortType {


    /**
     * Creates TD shipments.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.CreateShipmentResponse
     */
    @WebMethod(action = "urn:createShipmentTD")
    @WebResult(name = "CreateShipmentResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public CreateShipmentResponse createShipmentTD(
        @WebParam(name = "CreateShipmentTDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        CreateShipmentTDRequest part1);

    /**
     * Creates DD shipments.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.CreateShipmentResponse
     */
    @WebMethod(action = "urn:createShipmentDD")
    @WebResult(name = "CreateShipmentResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public CreateShipmentResponse createShipmentDD(
        @WebParam(name = "CreateShipmentDDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        CreateShipmentDDRequest part1);

    /**
     * Deletes the requested TD shipments.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.DeleteShipmentResponse
     */
    @WebMethod(action = "urn:deleteShipmentTD")
    @WebResult(name = "DeleteShipmentResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public DeleteShipmentResponse deleteShipmentTD(
        @WebParam(name = "DeleteShipmentTDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        DeleteShipmentTDRequest part1);

    /**
     * Deletes the requested DD shipments.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.DeleteShipmentResponse
     */
    @WebMethod(action = "urn:deleteShipmentDD")
    @WebResult(name = "DeleteShipmentResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public DeleteShipmentResponse deleteShipmentDD(
        @WebParam(name = "DeleteShipmentDDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        DeleteShipmentDDRequest part1);

    /**
     * Manifest the requested TD shipments.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.DoManifestResponse
     */
    @WebMethod(action = "urn:doManifestTD")
    @WebResult(name = "DoManifestResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public DoManifestResponse doManifestTD(
        @WebParam(name = "DoManifestTDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        DoManifestTDRequest part1);

    /**
     * Manifest the requested DD shipments.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.DoManifestResponse
     */
    @WebMethod(action = "urn:doManifestDD")
    @WebResult(name = "DoManifestResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public DoManifestResponse doManifestDD(
        @WebParam(name = "DoManifestDDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        DoManifestDDRequest part1);

    /**
     * Returns the request-url for getting a TD label.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.GetLabelResponse
     */
    @WebMethod(action = "urn:getLabelTD")
    @WebResult(name = "GetLabelResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public GetLabelResponse getLabelTD(
        @WebParam(name = "GetLabelTDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        GetLabelTDRequest part1);

    /**
     * Returns the request-url for getting a DD label.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.GetLabelResponse
     */
    @WebMethod(action = "urn:getLabelDD")
    @WebResult(name = "GetLabelResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public GetLabelResponse getLabelDD(
        @WebParam(name = "GetLabelDDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        GetLabelDDRequest part1);

    /**
     * Books a pickup order.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.BookPickupResponse
     */
    @WebMethod(action = "urn:bookPickup")
    @WebResult(name = "BookPickupResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public BookPickupResponse bookPickup(
        @WebParam(name = "BookPickupRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        BookPickupRequest part1);

    /**
     * Cancels a pickup order.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.CancelPickupResponse
     */
    @WebMethod(action = "urn:cancelPickup")
    @WebResult(name = "CancelPickupResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public CancelPickupResponse cancelPickup(
        @WebParam(name = "CancelPickupRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        CancelPickupRequest part1);

    /**
     * Returns the actual version of the implementation of the whole ISService webservice.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.GetVersionResponse
     */
    @WebMethod(action = "urn:getVersion")
    @WebResult(name = "GetVersionResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public GetVersionResponse getVersion(
        @WebParam(name = "Version", targetNamespace = "http://dhl.de/webservice/cisbase", partName = "part1")
        Version part1);

    /**
     * Returns the request-url for getting a TD export document.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.GetExportDocResponse
     */
    @WebMethod(action = "urn:getExportDocTD")
    @WebResult(name = "GetExportDocResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public GetExportDocResponse getExportDocTD(
        @WebParam(name = "GetExportDocTDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        GetExportDocTDRequest part1);

    /**
     * Returns the request-url for getting a DD  export document.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.GetExportDocResponse
     */
    @WebMethod(action = "urn:getExportDocDD")
    @WebResult(name = "GetExportDocResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public GetExportDocResponse getExportDocDD(
        @WebParam(name = "GetExportDocDDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        GetExportDocDDRequest part1);

    /**
     * Request the manifest.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.GetManifestDDResponse
     */
    @WebMethod(action = "urn:getManifestDD")
    @WebResult(name = "GetManifestDDResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public GetManifestDDResponse getManifestDD(
        @WebParam(name = "GetManifestDDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        GetManifestDDRequest part1);

    /**
     * Updates a DD shipment.
     * 
     * @param part1
     * @return
     *     returns intraship.ws.de.UpdateShipmentResponse
     */
    @WebMethod(action = "urn:updateShipmentDD")
    @WebResult(name = "UpdateShipmentResponse", targetNamespace = "http://de.ws.intraship", partName = "part1")
    public UpdateShipmentResponse updateShipmentDD(
        @WebParam(name = "UpdateShipmentDDRequest", targetNamespace = "http://de.ws.intraship", partName = "part1")
        UpdateShipmentDDRequest part1);

}
